"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ProviderBadge } from "@/components/ProviderBadge";
import { event } from "@/lib/analytics";
import { formatDate } from "@/lib/offers";
import type { ChangeType } from "@/types/change";

export type PublicChangeEntry = { id: string; offerId: string; provider: string; title: string; currentValue: string; previousValue?: string; observedAt: string; changeType: ChangeType; summary: string };
const filters: Array<{ value: string; label: string }> = [{value:"all",label:"All activity"},{value:"today",label:"Today"},{value:"week",label:"This week"},{value:"increased",label:"Increased"},{value:"decreased",label:"Decreased"},{value:"new",label:"New"},{value:"expired",label:"Expired"},{value:"reactivated",label:"Reactivated"},{value:"verified",label:"Recently verified"}];

export function ChangeFeedClient({ entries, today }: { entries: PublicChangeEntry[]; today: string }) {
  const [filter,setFilter] = useState("all");
  const visible = useMemo(() => entries.filter((entry) => { if(filter === "all") return true; if(filter === "today") return entry.observedAt.slice(0,10) === today; if(filter === "week") { const age = new Date(`${today}T00:00:00Z`).getTime() - new Date(entry.observedAt).getTime(); return age >= 0 && age <= 7*86400000; } return entry.changeType === filter; }),[entries,filter,today]);
  return <div><div className="flex flex-wrap gap-2" role="group" aria-label="Change feed filters">{filters.map((item) => <button key={item.value} aria-pressed={filter===item.value} onClick={() => {setFilter(item.value);event("filter_used",{filter_name:"change_feed",filter_value:item.value,source_page:"/recently-changed-offers"});}} className={`rounded-full px-4 py-2 text-sm font-extrabold ${filter===item.value?"bg-slate-950 text-white":"border border-slate-300 bg-white text-slate-700"}`}>{item.label}</button>)}</div><p className="mt-5 text-sm font-bold text-slate-500">{visible.length} reviewed records</p><div className="mt-4 grid gap-4 md:grid-cols-2">{visible.length ? visible.map((entry) => <article key={entry.id} className="premium-card rounded-3xl p-5"><div className="flex items-start gap-4"><ProviderBadge provider={entry.provider} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-extrabold uppercase tracking-wide text-slate-500">{entry.provider}</p><ChangeBadge type={entry.changeType} /></div><h2 className="mt-2 text-lg font-black text-slate-950">{entry.title}</h2></div></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className="text-sm font-bold text-slate-500">{entry.previousValue || "—"}</span><span className={`text-xl font-black ${entry.changeType==="decreased"?"text-red-600":"text-emerald-600"}`}>{entry.changeType === "decreased" ? "↓" : entry.changeType === "increased" ? "↑" : "→"}</span><span className="text-xl font-black text-slate-950">{entry.currentValue}</span></div><div className="mt-4 border-l-2 border-teal-300 pl-4"><p className="text-sm font-bold text-slate-800">Observed {formatDate(entry.observedAt.slice(0,10))}</p><p className="mt-1 text-sm leading-6 text-slate-600">{entry.summary}</p></div><Link href={`/offer/${entry.offerId}`} onClick={() => event("recently_changed_click",{offer_id:entry.offerId,change_type:entry.changeType})} className="mt-5 inline-flex rounded-full bg-blue-700 px-4 py-2 text-sm font-extrabold text-white">Review offer</Link></article>) : <div className="rounded-3xl bg-slate-100 p-8 text-center md:col-span-2"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-slate-950 text-2xl text-teal-300">◎</div><h2 className="mt-4 text-xl font-black">No approved records match this filter</h2><p className="mt-2 text-sm text-slate-600">Detected changes stay private until editorial review is complete.</p></div>}</div></div>;
}
function ChangeBadge({type}:{type:ChangeType}) { const color = type === "increased" || type === "new" || type === "reactivated" ? "bg-emerald-50 text-emerald-800" : type === "decreased" || type === "expired" ? "bg-red-50 text-red-800" : type === "needs-review" ? "bg-amber-50 text-amber-800" : "bg-teal-50 text-teal-800"; return <span className={`rounded-full px-3 py-1 text-xs font-bold ${color}`}>{type.replace("-"," ")}</span>; }
