import type { Metadata } from "next";
import Link from "next/link";
import { connection } from "next/server";
import { getAlertCounts } from "@/lib/alertStore";
import { CLARITY_PROJECT_ID, GA_MEASUREMENT_ID } from "@/lib/analytics";
import { firstPartyAnalyticsAvailable, getFirstPartyAnalytics } from "@/lib/firstPartyAnalytics";
import { hasOpsSession, opsConfigured } from "@/lib/opsAuth";
export const metadata:Metadata={title:"Product Analytics | OfferRadar Ops",robots:{index:false,follow:false}};
export default async function AnalyticsOpsPage(){await connection();const authenticated=await hasOpsSession();if(!opsConfigured()||!authenticated)return <main className="mx-auto max-w-4xl px-4 py-16"><Link href="/ops/changes" className="text-sm font-extrabold text-blue-700">Unlock via editorial queue</Link><h1 className="mt-4 text-4xl font-black">Product analytics is private</h1><p className="mt-3 text-slate-600">Configure `OPS_ACCESS_KEY` and unlock an ops session to view first-party engagement totals.</p></main>;const data=await getFirstPartyAnalytics();const alerts=await getAlertCounts();const metrics=[["Search visits",(data.sources.google||0)+(data.sources.bing||0)+(data.sources.other_search||0)],["Direct visits",data.sources.direct||0],["Offer-detail views",data.events.offer_detail_view||0],["Official-provider clicks",data.events.official_source_click||0],["Affiliate clicks",data.events.affiliate_click||0],["Watchlist saves",data.events.save_to_watchlist||0],["Alert subscriptions",data.events.alert_subscription||0],["Returning visits",data.returnState.returning||0],["Network referrals",data.events.network_outbound_click||0]];return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><Link href="/ops" className="text-sm font-extrabold text-blue-700">Ops dashboard</Link><p className="mt-5 text-xs font-extrabold uppercase tracking-wide text-teal-700">First-party product reporting</p><h1 className="mt-3 text-4xl font-black">Traffic, engagement, and conversion</h1><p className="mt-3 text-slate-600">Aggregate counts only—no notes, target values, email addresses, or persistent visitor IDs.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label,value])=><div key={String(label)} className="premium-card rounded-2xl p-5"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div><section className="mt-8 grid gap-5 md:grid-cols-3"><Config label="First-party events" value={firstPartyAnalyticsAvailable()?"Enabled":"Disabled"}/><Config label="Active alerts" value={String(alerts.active)}/><Config label="GA / Clarity" value={`${GA_MEASUREMENT_ID} · ${CLARITY_PROJECT_ID}`}/></section><section className="premium-card mt-8 rounded-3xl p-6"><h2 className="text-2xl font-black">Top recorded pages</h2><div className="mt-4 grid gap-2">{Object.entries(data.pages).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([page,count])=><div key={page} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{page}</span><strong>{count}</strong></div>)}</div><p className="mt-5 text-xs text-slate-500">Updated {data.updatedAt||"no first-party events recorded"}</p></section></main>}
function Config({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-2 font-black">{value}</p></div>}
